import typing as t

from cart.schemas import AddToCartDTO


class CartManagerI(t.Protocol):
    @classmethod
    def get_for_session(cls, session_id: str) -> t.Self: ...

    async def add(self, dto: AddToCartDTO): ...

    async def delete_by_id(self, product_id: int): ...

    async def update_qty_by_id(self, product_id: int, qty: int): ...

    async def check_exists(self, product_id: int): ...

    async def create(self, dto: AddToCartDTO): ...
