volumes:
  pg_data:
  redis_data:

services:
  web:
    container_name: gameshop_web
    ports:
      - "127.0.0.1:8000:8000"
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./media:/app/media
      - ./logs:/app/logs
    environment:
      - MODE=${MODE:?error}
    healthcheck:
      test: ["CMD-SHELL", "curl", "http://0.0.0.0:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
  parse_sales:
    container_name: gameshop_parse_sales
    build: 
      dockerfile: Dockerfile.parser
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MODE=${MODE:?error}
  postgres:
    container_name: gameshop_db
    image: postgres:17.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 3s
      retries: 5
    env_file:
      - .env

  redis:
    container_name: gameshop_redis
    image: redis/redis-stack:latest
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5
