volumes:
  pg_data:
  redis_data:
  loki_data:
  prometheus_data:
  grafana_data:

services:
  web:
    container_name: gameshop_web
    ports:
      - "127.0.0.1:8000:8000"
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./media:/app/media
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - MODE=${MODE:?error}
    healthcheck:
      test: ["CMD-SHELL", "curl", "http://0.0.0.0:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
  parse_sales:
    container_name: gameshop_parse_sales
    build: 
      dockerfile: Dockerfile.parser
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MODE=${MODE:?error}
    profiles: [optional]
  postgres:
    container_name: gameshop_db
    image: postgres:17.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 3s
      retries: 5
    env_file:
      - .env

  redis:
    container_name: gameshop_redis
    image: redis/redis-stack:latest
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 5

  # alloy:
  #   container_name: gameshop_alloy
  #   image: grafana/alloy:latest
  #   volumes:
  #     - ${ALLOY_CONFIG_PATH}:/etc/alloy/config.alloy
  #   ports:
  #     - "127.0.0.1:12345:12345"
  #   env:
  #     ALLOY_CONFIG_PATH: ./cfg.alloy

  grafana:
    container_name: gameshop_grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./devops/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    env_file:
      - .env
    
  loki:
    container_name: gameshop_loki
    image: grafana/loki:latest
    volumes:
      - loki_data:/loki
      # - ./devops/loki-cfg.yaml:/etc/loki/local-config.yaml

  prometheus:
    image: prom/prometheus:latest
    container_name: gameshop_prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./devops/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
