volumes:
  pg_data:

services:
  web:
    container_name: gameshop_web
    ports:
      - "8000:8000"
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    environment:
      - MODE=prod
    healthcheck:
      test: ["CMD-SHELL", "curl", "http://0.0.0.0:8000/ping"]
      interval: 2s
      timeout: 3s
      retries: 5
  postgres:
    container_name: gameshop_db
    image: postgres:17.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5
    env_file:
      - .env
