"""removed SteamGiftOrder.percent_fee

Revision ID: 4e31f195cd74
Revises: c00121503172
Create Date: 2025-04-02 17:45:56.412137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e31f195cd74'
down_revision: Union[str, None] = 'c00121503172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steam_gift_order', 'percent_fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steam_gift_order', sa.Column('percent_fee', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
