"""initial

Revision ID: 53fe3dc0866b
Revises:
Create Date: 2024-12-03 22:12:48.396101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53fe3dc0866b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "platform",
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.Column("platform_name", sa.String(), nullable=False),
        sa.Column("photo_url", sa.String(), nullable=False),
        sa.Column("regular_price", sa.Numeric(), nullable=False),
        sa.Column("delivery_method", sa.String(), nullable=False),
        sa.Column("discount", sa.Integer(), nullable=False),
        sa.Column("discount_valid_to", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            server_onupdate=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_method = ANY (ARRAY['activation_key', 'replenishment_card', 'account_purchase']::text[])"
        ),
        sa.ForeignKeyConstraint(
            ["category_name"], ["category.name"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["platform_name"], ["platform.name"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "category_name", "platform_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    op.drop_table("platform")
    op.drop_table("category")
    # ### end Alembic commands ###
