"""upgraded product_on_sale

Revision ID: 54954f5403c0
Revises: b7311e1005a3
Create Date: 2025-02-28 12:52:15.354920

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "54954f5403c0"
down_revision: Union[str, None] = "b7311e1005a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_category_enum_members = ("XBOX", "PSN")
_product_on_sale_category_enum = postgresql.ENUM(
    *_category_enum_members, name="productonsalecategory"
)


def upgrade() -> None:
    _product_on_sale_category_enum.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_on_sale", sa.Column("base_price", sa.Float(), nullable=False)
    )
    op.add_column(
        "product_on_sale", sa.Column("base_price_currency", sa.String(), nullable=False)
    )
    op.add_column("product_on_sale", sa.Column("with_gp", sa.Boolean(), nullable=True))
    op.add_column(
        "product_on_sale", sa.Column("discounted_price", sa.Float(), nullable=False)
    )
    op.add_column(
        "product_on_sale",
        sa.Column("discounted_price_currency", sa.String(), nullable=False),
    )
    op.add_column(
        "product_on_sale", sa.Column("discount", sa.Integer(), nullable=False)
    )
    op.add_column(
        "product_on_sale", sa.Column("image_url", sa.String(), nullable=False)
    )
    op.add_column("product_on_sale", sa.Column("region", sa.String(), nullable=False))
    op.add_column(
        "product_on_sale",
        sa.Column(
            "category",
            sa.Enum(*_category_enum_members, name="productonsalecategory"),
            nullable=False,
        ),
    )
    op.drop_column("product_on_sale", "photo_url")
    op.drop_column("product_on_sale", "price")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_on_sale",
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "product_on_sale",
        sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("product_on_sale", "category")
    _product_on_sale_category_enum.drop(op.get_bind())
    op.drop_column("product_on_sale", "region")
    op.drop_column("product_on_sale", "image_url")
    op.drop_column("product_on_sale", "discounted_price_currency")
    op.drop_column("product_on_sale", "discounted_price")
    op.drop_column("product_on_sale", "base_price_currency")
    op.drop_column("product_on_sale", "base_price")
    op.drop_column("product_on_sale", "discount")
    op.drop_column("product_on_sale", "with_gp")
    # ### end Alembic commands ###
