"""new product on sale model

Revision ID: 6238a75a8bfe
Revises: 5d2acaf5e971
Create Date: 2025-02-01 10:44:55.187292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6238a75a8bfe"
down_revision: Union[str, None] = "5d2acaf5e971"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_on_sale",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("deal_until", sa.DateTime(), nullable=True),
        sa.Column("photo_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_on_sale")
    # ### end Alembic commands ###
