"""new product.in_stock column

Revision ID: 73824129f4a8
Revises: 6238a75a8bfe
Create Date: 2025-02-07 20:33:29.118312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "73824129f4a8"
down_revision: Union[str, None] = "6238a75a8bfe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "in_stock", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product", "in_stock")
    # ### end Alembic commands ###
