"""Merged CustomerData into Order model

Revision ID: 7384c8e447f9
Revises: 255990c637c4
Create Date: 2025-01-09 15:04:30.368084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7384c8e447f9"
down_revision: Union[str, None] = "255990c637c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("order_customer_data_id_fkey", "order", type_="foreignkey")
    op.drop_column("order", "customer_data_id")
    op.drop_table("customer_data")
    op.add_column("order", sa.Column("customer_email", sa.String(), nullable=True))
    op.add_column("order", sa.Column("user_id", sa.Integer(), nullable=True))
    op.add_column("order", sa.Column("customer_phone", sa.String(), nullable=True))
    op.add_column("order", sa.Column("customer_name", sa.String(), nullable=False))
    op.create_check_constraint(
        None,
        "order",
        "(customer_email IS NOT NULL AND customer_name IS NOT NULL) OR user_id IS NOT NULL",
    )
    op.create_foreign_key(
        None, "order", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "customer_data_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "order", type_="foreignkey")
    op.drop_constraint(None, "order", type_="check")
    op.create_foreign_key(
        "order_customer_data_id_fkey",
        "order",
        "customer_data",
        ["customer_data_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("order", "customer_name")
    op.drop_column("order", "customer_phone")
    op.drop_column("order", "user_id")
    op.drop_column("order", "customer_email")
    op.create_table(
        "customer_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.CheckConstraint(
            "email IS NOT NULL OR user_id IS NOT NULL", name="customer_data_check"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="customer_data_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="customer_data_pkey"),
    )
    # ### end Alembic commands ###
