"""new column Order.customer_tg_username

Revision ID: 74740999d7fd
Revises: 7384c8e447f9
Create Date: 2025-01-12 13:59:59.504596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74740999d7fd"
down_revision: Union[str, None] = "7384c8e447f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order", sa.Column("customer_tg_username", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "customer_tg_username")
    # ### end Alembic commands ###
