"""removed unique index user.username

Revision ID: 88cf604daf6d
Revises: 73824129f4a8
Create Date: 2025-02-08 12:38:47.200453

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88cf604daf6d"
down_revision: Union[str, None] = "73824129f4a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_username_key", "user", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("user_username_key", "user", ["username"])
    # ### end Alembic commands ###
