"""removed product_on_sale

Revision ID: 8ede77519793
Revises: ca60a9fe89f5
Create Date: 2025-03-06 19:42:13.478239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ede77519793"
down_revision: Union[str, None] = "ca60a9fe89f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_on_sale")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_on_sale",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "deal_until", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "base_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "base_price_currency", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("with_gp", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "discounted_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "discounted_price_currency",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("discount", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("image_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "category",
            postgresql.ENUM("XBOX", "PSN", name="productonsalecategory"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="product_on_sale_pkey"),
    )
    # ### end Alembic commands ###
