"""new User.username column

Revision ID: a870a2b26dbe
Revises: 74740999d7fd
Create Date: 2025-01-19 14:07:11.115677

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a870a2b26dbe"
down_revision: Union[str, None] = "74740999d7fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("order", "customer_name", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column("user", sa.Column("username", sa.String(), nullable=False))
    op.create_unique_constraint(None, "user", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "username")
    op.alter_column(
        "order", "customer_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
