"""removed product.delivery_method column

Revision ID: abab96077f95
Revises: 9f479f4a0af1
Create Date: 2025-03-19 18:27:41.391916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abab96077f95'
down_revision: Union[str, None] = '9f479f4a0af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'delivery_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('delivery_method', postgresql.ENUM('KEY', 'ACCOUNT_PURCHASE', 'GIFT', name='productdeliverymethod'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
