"""upgraded steam_top_up model

Revision ID: ad925e19bf90
Revises: d32fd528f162
Create Date: 2025-03-15 18:48:10.357249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad925e19bf90"
down_revision: Union[str, None] = "d32fd528f162"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "steam_top_up", sa.Column("customer_email", sa.String(), nullable=True)
    )
    op.add_column("steam_top_up", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "steam_top_up", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_check_constraint(None, "steam_top_up", "amount > 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "steam_top_up", type_="foreignkey")
    op.drop_column("steam_top_up", "user_id")
    op.drop_column("steam_top_up", "customer_email")
    op.drop_constraint(None, "steam_top_up", type_="check")
    # ### end Alembic commands ###
