"""new token.scope column

Revision ID: b7311e1005a3
Revises: 88cf604daf6d
Create Date: 2025-02-17 16:12:58.817674

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "b7311e1005a3"
down_revision: Union[str, None] = "88cf604daf6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_token_scopes = postgresql.ENUM("ACTIVATION", "PASSWORD_RESET", name="tokenscopes")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _token_scopes.create(op.get_bind())
    op.add_column(
        "token",
        sa.Column(
            "scope",
            sa.Enum("ACTIVATION", "PASSWORD_RESET", name="tokenscopes"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token", "scope")
    _token_scopes.drop(op.get_bind())
    # ### end Alembic commands ###
