"""Updated platform and category models to include id column and made it pk instead of name

Revision ID: b94aba01f92b
Revises: 0f04217acfad
Create Date: 2024-12-08 20:08:39.711703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94aba01f92b'
down_revision: Union[str, None] = '0f04217acfad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))
    op.add_column('platform', sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))
    op.drop_constraint('product_category_name_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_platform_name_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'category_name')
    op.drop_column('product', 'platform_name')
    op.drop_constraint('category_pkey', 'category', type_="primary")
    op.drop_constraint('platform_pkey', 'platform', type_="primary")
    op.create_primary_key(None, "platform", ["id"])
    op.create_primary_key(None, "category", ["id"])
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('platform_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'product', ['name', 'category_id', 'platform_id'])
    op.create_foreign_key(None, 'product', 'platform', ['platform_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_platform_name_fkey', 'product', 'platform', ['platform_name'], ['name'], ondelete='CASCADE')
    op.create_foreign_key('product_category_name_fkey', 'product', 'category', ['category_name'], ['name'], ondelete='CASCADE')
    op.drop_constraint(None, 'product', type_='unique')
    op.create_unique_constraint('product_name_category_name_platform_name_key', 'product', ['name', 'category_name', 'platform_name'])
    op.drop_column('product', 'platform_id')
    op.drop_column('product', 'category_id')
    op.drop_column('platform', 'id')
    op.drop_column('category', 'id')
    # ### end Alembic commands ###
