"""Moved product delivery methods into separate model, new url field in category, platform, delivery_method models

Revision ID: b9c54e95fbd0
Revises: 0f04217acfad
Create Date: 2024-12-16 16:45:41.698078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9c54e95fbd0'
down_revision: Union[str, None] = '0f04217acfad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.add_column('category', sa.Column('url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'category', ['url'])
    op.add_column('platform', sa.Column('url', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'platform', ['url'])
    op.add_column('product', sa.Column('delivery_method_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'delivery_method', ['delivery_method_id'], ['id'], ondelete='CASCADE')
    op.drop_column('product', 'delivery_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('delivery_method', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'delivery_method_id')
    op.drop_constraint(None, 'platform', type_='unique')
    op.drop_column('platform', 'url')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'url')
    op.drop_table('delivery_method')
    # ### end Alembic commands ###
