"""new order_item.region column

Revision ID: ba08e7b814a5
Revises: 9bf609c8f9b8
Create Date: 2025-03-14 20:05:42.479764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba08e7b814a5"
down_revision: Union[str, None] = "9bf609c8f9b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("delivery_method")
    op.drop_table("category")
    op.drop_table("platform")
    op.add_column("order_item", sa.Column("region", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_item", "region")
    op.create_table(
        "platform",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="platform_pkey"),
        sa.UniqueConstraint("url", name="platform_url_key"),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="category_pkey"),
        sa.UniqueConstraint("url", name="category_url_key"),
    )
    op.create_table(
        "delivery_method",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="delivery_method_pkey"),
        sa.UniqueConstraint("url", name="delivery_method_url_key"),
    )
    # ### end Alembic commands ###
