"""new steam_gift_order model

Revision ID: c00121503172
Revises: abab96077f95
Create Date: 2025-03-31 15:22:17.925880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from products.models import ProductCategory, ProductPlatform


# revision identifiers, used by Alembic.
revision: str = "c00121503172"
down_revision: Union[str, None] = "abab96077f95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steam_gift_order",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("percent_fee", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("friend_link", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["base_order.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint("in_app_order_id_fkey", "in_app_order", type_="foreignkey")
    op.create_foreign_key(
        None, "in_app_order", "base_order", ["id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("product", sa.Column("sub_id", sa.Integer(), nullable=True))
    op.drop_constraint(
        "steam_top_up_order_id_fkey", "steam_top_up_order", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "steam_top_up_order", "base_order", ["id"], ["id"], ondelete="CASCADE"
    )
    op.create_check_constraint(
        "product_sub_id_check",
        "product",
        sa.text(
            "(platform = :steam_platform AND category = :games_cat AND sub_id IS NOT NULL) OR (platform != :steam_platform OR category != :games_cat AND sub_id IS NULL)"
        ).bindparams(
            steam_platform=ProductPlatform.STEAM.name,
            games_cat=ProductCategory.GAMES.name,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "steam_top_up_order", type_="foreignkey")
    op.create_foreign_key(
        "steam_top_up_order_id_fkey", "steam_top_up_order", "base_order", ["id"], ["id"]
    )
    op.drop_column("product", "sub_id")
    op.drop_constraint(None, "in_app_order", type_="foreignkey")
    op.create_foreign_key(
        "in_app_order_id_fkey", "in_app_order", "base_order", ["id"], ["id"]
    )
    op.drop_table("steam_gift_order")
    op.drop_constraint("product_sub_id_check", "product")
    # ### end Alembic commands ###
