"""extended order model with columns containing payment related info

Revision ID: ca60a9fe89f5
Revises: 54954f5403c0
Create Date: 2025-03-02 11:15:20.675175

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from payments.models import AvailablePaymentSystems


# revision identifiers, used by Alembic.
revision: str = "ca60a9fe89f5"
down_revision: Union[str, None] = "54954f5403c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

payments_enum = postgresql.ENUM(AvailablePaymentSystems, name="availablepaymentsystems")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    payments_enum.create(op.get_bind())
    op.add_column("order", sa.Column("bill_id", sa.String(), nullable=True))
    op.add_column(
        "order",
        sa.Column(
            "paid_with",
            sa.Enum(AvailablePaymentSystems, name="availablepaymentsystems"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "paid_with")
    op.drop_column("order", "bill_id")
    payments_enum.drop(op.get_bind())
    # ### end Alembic commands ###
