"""new steam_top_up model

Revision ID: d32fd528f162
Revises: ba08e7b814a5
Create Date: 2025-03-15 16:03:14.992524

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from orders.models import OrderStatus
from payments.models import AvailablePaymentSystems


# revision identifiers, used by Alembic.
revision: str = "d32fd528f162"
down_revision: Union[str, None] = "ba08e7b814a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_status_enum = postgresql.ENUM(OrderStatus, name="orderstatus")
_payment_systems_enum = postgresql.ENUM(
    AvailablePaymentSystems, name="availablepaymentsystems"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "steam_top_up",
        sa.Column("steam_login", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("percent_fee", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "order_date",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("bill_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "steam_top_up",
        sa.Column(
            "status",
            _status_enum,
            server_default=sa.text("'PENDING'"),
            nullable=False,
        ),
    )
    op.add_column(
        "steam_top_up",
        sa.Column(
            "paid_with",
            _payment_systems_enum,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("steam_top_up")
    # ### end Alembic commands ###
