"""new column news.title

Revision ID: d3f0d91e7889
Revises: c8575bc64f2a
Create Date: 2024-12-24 16:12:28.535850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f0d91e7889'
down_revision: Union[str, None] = 'c8575bc64f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'title')
    # ### end Alembic commands ###
