"""renamed product.photo_url to image_url

Revision ID: dc802e700bc4
Revises: 53fe3dc0866b
Create Date: 2024-12-04 18:26:11.577675

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dc802e700bc4'
down_revision: Union[str, None] = '53fe3dc0866b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "photo_url", new_column_name="image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("product", "image_url", new_column_name="photo_url")

    # ### end Alembic commands ###
