"""new steam_gift_order.total field

Revision ID: f3315acffeef
Revises: f47b6ea55974
Create Date: 2025-04-10 16:56:37.221735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f3315acffeef"
down_revision: Union[str, None] = "f47b6ea55974"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("steam_gift_order", sa.Column("total", sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("steam_gift_order", "total")
    # ### end Alembic commands ###
