"""returned back product.delivery_method col

Revision ID: f47b6ea55974
Revises: 4e31f195cd74
Create Date: 2025-04-07 14:45:32.406326

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f47b6ea55974"
down_revision: Union[str, None] = "4e31f195cd74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product",
        sa.Column(
            "delivery_method",
            sa.Enum(
                "KEY",
                "ACCOUNT_PURCHASE",
                "NEW_ACCOUNT_PURCHASE",
                "GIFT",
                name="productdeliverymethod",
            ),
            nullable=False,
        ),
    )
    op.alter_column(
        "regional_price", "converted_from_curr", new_column_name="original_curr"
    )
    op.alter_column(
        "token",
        "expiry",
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "token",
        "expiry",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "regional_price", "original_curr", new_column_name="converted_from_curr"
    )
    op.drop_column("product", "delivery_method")
    # ### end Alembic commands ###
