class DatabaseError(Exception): ...


class DBConnectionError(DatabaseError): ...


class NotFoundError(DatabaseError): ...


class AlreadyExistsError(DatabaseError): ...


class RelatedResourceNotFoundError(DatabaseError): ...
