name: CI
on:
  push:
    branches:
      - 'dev'

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4
     - name: Install dependencies
       run: pip install poetry && poetry install
     - name: lint
       run: poetry run ruff check ./src --fix
     - name: type checking
       run: poetry run pyright ./src
  # test:
  #   needs: [quality-check]
  #   runs-on: ubuntu-latest
  #   steps:
  #    - name: Checkout
  #      uses: actions/checkout@v4
  #    - name: Build and run docker compose
  #      run: MODE=tests docker compose up --build -d
  #    - name: Run tests
  #      run: MODE=tests make run/tests/docker
  #
